config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'about' => 'page#about', as: :about
  get 'blogs' => 'page#blogs', as: :blogs
  # get 'portfolio/'=> 'projects#index', as: :portfolio
  # get 'resume' => 'page#resume', as: :resume
  # get 'contact' => 'page#contact', as: :contact

  get 'portfolio/guess-that-word' => 'snowman#index'
  get 'portfolio/snowman/word/retrieve' => 'snowman#retrieve'
  get 'portfolio/battleship' => 'battleship#index'


end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/battleship_controller.rb
class BattleshipController < ApplicationController
	layout 'battleship'
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  layout 'application'

  def home
  	last_blog = Blog.all.last
    projects = Project.all
    @content = {last_blog:last_blog, projects: projects}
  end

  def blogs
  	@blogs = Blog.all.reverse
  end

  def resume
     # pdf_filename = Rails.root.join("public", "resume.pdf")
     # send_file(pdf_filename, :filename => "resume.pdf", :disposition => "inline", :type => "application/pdf")
  end
end
 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index 
    redirect_to root_path

  end

  # GET /projects/1
  def show
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:type, :picture_url, :techologies_used)
    end
end

app/controllers/snowman_controller.rb
class SnowmanController < ApplicationController
	layout 'snowman'

	def retrieve
		if params["category"] == 'random'
			category = select_random_category
			words = Word.where(category: category)
			@word = words.sample
		else
			words = Word.where(category: params["category"])
			@word = words.sample
		end
		render json: @word
	end


	private

	def select_random_category
		categories =['desserts', 'mammals', 'sports', 'countries']
		categories.sample
	end

	def select_random_word(category)
		category.sample
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battleship_helper.rb
module BattleshipHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/snowman_helper.rb
module SnowmanHelper
end

app/views/battleship/index.html.erb
<%= react_component 'BattleshipPage' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emilio Corpus</title>
  <%= stylesheet_link_tag "application"%>
  <%= stylesheet_link_tag "scaffolds"%>
  <%= stylesheet_link_tag "page"%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= yield %>
	<%= render 'partials/footer' %>
</body>
</html>

app/views/layouts/battleship.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleship on React.js</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag "battleship"%>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/layouts/snow.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleship with React.js</title>
  <%= stylesheet_link_tag 'application'%>
  <%= stylesheet_link_tag 'scaffolds'%>
  <%= stylesheet_link_tag 'hangman'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Cormorant+SC|Sanchez" rel="stylesheet">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<body>
		<%= yield %>
	</body>
</html>

app/views/layouts/snowman.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guess That Word</title>
  <%= stylesheet_link_tag 'application'%>
  <%= stylesheet_link_tag 'scaffolds'%>
  <%= stylesheet_link_tag 'snowman'%>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/css?family=Cormorant+SC|Sanchez" rel="stylesheet">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<body>
		<%= yield %>
    <%= render 'partials/footer' %>
	</body>
</html>

app/views/page/about.html.erb
<div class="body-container debugger">

	<div class="about-container debugger"

		<h1></h1>
			<p>Hey, I am Emilio! I am a web developer who is looking for opportunies to sharpen my craft. If you would like to work with me please shoot me an email at abc@abc.com !
			</p>

			My expertise include:
			
	

	</div>

</div>

app/views/page/blogs.html.erb
<%= render 'partials/navbar_blogs' %>
<div class="body-container debugger"> 
	<div class ="blogs-container">
		<% @blogs.each do |blog| %>
			<div class=" blog">
				<p class="blog-title">
					<%= blog.title %>
				</p>
				<hr />
				<p class="blog-date">
					<%= blog.created_at.strftime("%A") %>, 
					<%= blog.created_at.strftime("%B #{blog.created_at.day.ordinalize}, %Y")%>
				</p>
				<p class="blog-content">
					<%= blog.content %>
				</p>
			</div>
		<% end %>
	</div>
</div>

app/views/page/home.html.erb
<%= render 'partials/navbar_home' %>
<div class="upper-body-container">
	<div class="welcome" >
		<div id="welcome-splash" class="hidden">
			<h2>Full-Stack Web Developer</h2>
			<h2>Bay Area Native</h2>
			<h2>Lifelong Learner</h2>
			<h2>Adventure Seeker</h2>
		</div>
		<div class="arrow-link-container hidden">
			<a href="#about-blogs" class="arrow-links" data-target="about-blogs">LEARN MORE<br/>
				<span style="font-size:20px">&#8595;</span>
			</a>
		</div>
	</div>
	<div class="divider" id="about-blogs">
		<div>
			<h3>A B O U T &nbsp; M E </h3>
		</div>
	</div>
</div>
<div class="upper-mid-body-container">
	<!-- <div class ="blogs-container"> -->
	<!-- 	<div class="latest-blog ">
			<p class="blog-title">
				MOST RECENT BLOG:
				<%= @content[:last_blog][:name]%>
			</p>
			<hr />
			<p class="blog-date">
				<%= @content[:last_blog].created_at.strftime("%A") %>, 
				<%= @content[:last_blog].created_at.strftime("%B #{@content[:last_blog].created_at.day.ordinalize}, %Y")%>
			</p>
			<p class="blog-content">
				<%= @content[:last_blog].content %>
			</p>
		</div>
 -->
	<div class="about-me-summary ">
		<div class="about-me-pic-container">
			<img src="assets/ecorpus.png">
		</div>
		<div class="about-me-summary-info">
			<p class="about-me-summary-text">
				<h3>Emilio Corpus</h3>
				Bay Area Native | Ruby on Rails Afficianado | Object Oriented Progammer | Critical Thinker | Engineering Empathy 
			</p>
		</div>
		<div style="width:100%;text-align:center;">
			<a href="www.linkedin.com/emiliocorpus">
				<img src="assets/linkedin-icon.png" class="sn-icon"/>
			</a>
			<a href="www.github.com/">
				<img src="assets/github-icon.png" class="sn-icon"/>
			</a>
		</div>

		<div class="learn-more-about" style="padding-top:3%;">
			<a href="#more-about-me" class='more-about-me' data-target="more-about-me">
				Expand<br/>
				&#8595;
			</a>

			<a href="#hide-about-me" class="hide-more-about-me" data-target="hide-about-me">
				&#8593;<br/>
				Collapse
			</a>
		</div>

		<div id="more-about-me">
			<h3>ABOUT</h3>
			<p id="about-emilio-full">
			Emilio is a full stack web developer who is interested in designing/creating applications to help develop a more efficient society. He is currently seeking full-time employment and is looking for any position that will allow him to grow and expand his current technical capacities. He is mostly experienced with Ruby on Rails and also React.js
			<br/><br/>
			Prior to his interest in web development, Emilio had aspirations to become a medical doctor. With this in mind he attended UC Irvine where he received his bachelor’s in Biology. For several years after college, Emilio worked as an emergency room scribe to help enhance his medical knowledge. However, it was there that he learned he was no longer as passionate about healthcare as he once was. It was then that he decided to look toward another career path... progamming!
			<br/> <br/>
			After talking to several friends with computer science backgrounds and completing <a href="https://www.codecademy.com/">codecademy.com</a> web dev tutorials, he decided to attend DevBootcamp’s program in San Francisco. There he acquired even more skills in web development and today uses his knowledge to design/create various Ruby on Rails applications. Being fairly new to the web development community, Emilio prides himself in learning new technologies on the fly and considers himself an efficient problem solver.
			<br/> <br/>
			Outside of the matrix, Emilio loves going on hikes, playing basketball with friends, and traveling to the unknown. He is an Oakland Raiders die-hard fan, amateur ukulele musician, and current PokemonGO trainer.</p>
		</div>
		<!-- </div> -->
	</div>


	<div class="divider" id="portfolio">
			<div>
				<h3>P O R T F O L I O</h3>
			</div>
	</div>
</div>
<div class="lower-mid-body-container">
	<div class="portfolio-container">
		<div style="vertical-align:middle;text-align:center;width:100%;margin:0 auto;padding-top:100px;padding-bottom:100px;" class="">
			<% @content[:projects].each do |project| %>
			<div class="project">
				<p class="project-title">
					<h5><%= project.name %></h5>
				</p>
				<hr/>
				<div class ="project-picture">
					<a href=<%= project.url %>>
					<img src=<%= 'assets/' + project.picture_url %> / >
					</a>
				</div>

				<hr/>

				<p class="project-description">
					<%= project.description %>
				</p>
				<hr />
				<p class="project-link">
					<a href=<%= project.url %>>View Project</a>
				</p>
			</div>
			<%end %>
		</div>
	</div>
	
	<div class="divider" id="skillset">
				<div>
					<h3>S K I L L S E T</h3>
				</div>
		</div>
	
</div>

<div class="lower-body-container">
	<div class="skills-icons-container">
		<div class="skill-icon-pic-container" title="HTML5">
			<img src="assets/html.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="CSS3">
			<img src="assets/css.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="Javascript">
			<img src="assets/javascript.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="React.js">
			<img src="assets/react.png"/>
		</div>

		<div class="skill-icon-pic-container jquery-pic" title="Jquery">
			<img src="assets/jquery-icon.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="Ruby on Rails">
			<img src="assets/ruby-on-rails.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="Ruby">
			<img src="assets/ruby.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="PostgreSQL">
			<img src="assets/postgreSQL.png" style="height:110px;"/>
		</div>
		
		<div class="skill-icon-pic-container" title="Github">
			<img src="assets/git.png"/>
		</div>
		
		<div class="skill-icon-pic-container" title="Heroku">
			<img src="assets/heroku.png"/>
		</div>
	</div>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
	<div class="footer-content">
		&copy; All rights reserved <br/>
		Want to work with me? <br/>
		Contact<br/>
		<a href="mailto:emiliocorpus@gmail.com">emiliocorpus@gmail.com</a> | <a href='https://www.github.com'>github</a> | <a href="https://www.linkedin.com">linkedin</a>
	</div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#about-me" data-target="about-blogs">About Me</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#blogs" data-target="about-blogs">Blogs</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#portfolio" data-target="portfolio">Portfolio</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#resume" data-target="resue">Resume</a>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_about.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="text-center nav-custom-color active">
            <%= link_to 'About Me',  about_path%>
          </li>
          <li class="text-center nav-custom-color">
          <%= link_to 'Blogs', blogs_path %>
          </li>
          <li class="text-center nav-custom-color">
            <%= link_to 'Portfolio', portfolio_path %>
          </li>
          <li class="text-center nav-custom-color">
            <%= link_to 'Resume', resume_path %>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_blogs.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="text-center nav-custom-color">
            <%= link_to 'About Me',  about_path%>
          </li>
          <li class="text-center nav-custom-color active">
          <%= link_to 'Blogs', blogs_path %>
          </li>
          <li class="text-center nav-custom-color">
            <%= link_to 'Portfolio', portfolio_path %>
          </li>
          <li class="text-center nav-custom-color">
            <%= link_to 'Resume', resume_path %>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_home.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#about-me" data-target="about-blogs">About Me</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#portfolio" data-target="portfolio">Portfolio</a>
          </li>
          <li class="text-center nav-custom-color">
            <a href="/assets/resume.pdf" target="_blank">Résumé</a>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_portfolio.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#about-me" data-target="about-blogs">About Me</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#blogs" data-target="about-blogs">Blogs</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#portfolio" data-target="portfolio">Portfolio</a>
          </li>
          <li class="text-center nav-custom-color active">
            <a class="searchbychar" href="#resume" data-target="resue">Resume</a>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_navbar_resume.html.erb
<nav class="navbar-fixed-top navbar-default nav-down">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EMILIO CORPUS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="text-center nav-custom-color">
            <%= link_to 'Home', root_path %>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#about-me" data-target="about-blogs">About Me</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#blogs" data-target="about-blogs">Blogs</a>
          </li>
          <li class="text-center nav-custom-color">
            <a class="searchbychar" href="#portfolio" data-target="portfolio">Portfolio</a>
          </li>
          <li class="text-center nav-custom-color active">
            <a class="searchbychar" href="#resume" data-target="resue">Resume</a>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url %>
  </div>
  <div class="field">
    <%= f.label :techologies_used %><br>
    <%= f.text_area :techologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/battleship.html.erb
Welcome to the battleship.html.erb

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'partials/navbar_portfolio' %>


<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Picture url</th>
      <th>Techologies used</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.type %></td>
        <td><%= project.picture_url %></td>
        <td><%= project.techologies_used %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/snowman.html.erb
Welcome to the snowman.html.erb

app/views/snowman/index.html.erb
<%= react_component 'HangmanPage' %>